eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      # dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
